/**
 * Type definitions for prompt system
 */

// ============================================================================
// Version Management
// ============================================================================

export interface PromptVersion {
  version: string // Semantic versioning (e.g., "1.0.0")
  releaseDate: Date
  status: 'active' | 'deprecated' | 'experimental'
  changelog: string[]
  author: string
  migrationNotes?: string
}

// ============================================================================
// Story Generation
// ============================================================================

export interface StoryGenerationInput {
  characterName: string
  characterAge: number
  characterGender: 'boy' | 'girl' | 'other'
  theme: string
  illustrationStyle: string
  customRequests?: string
  referencePhotoAnalysis?: CharacterAnalysis // Optional: kept for backward compatibility, but not required
  language?: 'en' | 'tr' | 'de' | 'fr' | 'es' | 'zh' | 'pt' | 'ru'
  pageCount?: number // Debug: Optional page count override (3-20)
  // Step 1 data (preferred, no AI Analysis needed)
  hairColor?: string
  eyeColor?: string
  /** Faz 1: Master karakterin kilitli kıyafeti; story tüm sayfalarda bunu kullanır. */
  defaultClothing?: string
  // NEW: Multiple characters support
  characters?: Array<{
    id: string
    name: string // Ana karakter için Step 1'den, diğerleri için tip adı
    type: {
      group: string
      value: string
      displayName: string
    }
    characterId?: string // API'den gelen karakter ID'si
  }>
}

export interface StoryGenerationOutput {
  title: string
  /** Plan A: One sentence English, setting/background only for book cover. Generated by story LLM. COVER_PATH_FLOWERS_ANALYSIS.md §7 */
  coverSetting?: string
  pages: StoryPage[]
  totalPages: number
  /** NEW: Supporting entities (animals, objects) in the story - for master generation */
  supportingEntities?: SupportingEntity[]
  metadata: {
    ageGroup: string
    readingTime: number
    educationalThemes: string[]
    safetyChecked: boolean
  }
}

/**
 * Supporting entity in the story (animals, objects, etc.)
 * Used to generate master illustrations for consistency
 */
export interface SupportingEntity {
  id: string // Unique ID (e.g., "rabbit-001", "ball-001")
  type: 'animal' | 'object' // Entity type
  name: string // Entity name (e.g., "Fluffy the Rabbit", "Magic Ball")
  description: string // Brief description for master generation (e.g., "white rabbit with long ears")
  appearsOnPages: number[] // Which pages this entity appears on
}

/** A5: Optional per-page shot plan from story LLM. When present, image prompt uses these instead of code-derived values. */
export interface ShotPlan {
  shotType?: string // e.g. "wide establishing", "wide shot"
  lens?: string // e.g. "24-28mm", "35mm"
  cameraAngle?: string // e.g. "eye-level", "slightly above ground"
  placement?: string // e.g. "left third", "lower-right third"
  timeOfDay?: string // e.g. "morning", "golden hour", "day", "dusk"
  mood?: string // e.g. "wonder", "exciting", "calm"
}

export interface StoryPage {
  pageNumber: number
  text: string
  imagePrompt: string
  sceneDescription: string
  characterIds: string[] // NEW: Which character(s) appear on this page (character IDs) - REQUIRED
  /** Story-driven clothing per page (e.g. astronaut suit, swimwear). Plan: Kapak/Close-up/Kıyafet. */
  clothing?: string
  /** A5: Optional shot plan from LLM; when set, image prompt uses these for SHOT PLAN block. */
  shotPlan?: ShotPlan
}

export interface AgeGroupRules {
  minAge: number
  maxAge: number
  complexity: 'very-simple' | 'simple' | 'moderate' | 'advanced'
  vocabulary: 'basic' | 'intermediate' | 'advanced'
  sentenceLength: 'short' | 'medium' | 'long'
  themes: string[]
  avoidThemes: string[]
  educationalFocus: string[]
}

export interface ThemeConfig {
  name: string
  category: 'adventure' | 'fantasy' | 'educational' | 'daily-life' | 'animals'
  mood: 'exciting' | 'calm' | 'funny' | 'mysterious' | 'inspiring'
  setting: string
  commonElements: string[]
  avoidElements: string[]
  colorPalette: string[]
}

export interface SafetyRules {
  mustInclude: string[]
  mustAvoid: string[]
  contentFlags: string[]
  parentalGuidance: boolean
}

// ============================================================================
// Image Generation
// ============================================================================

export interface ImageGenerationInput {
  prompt: string
  characterDescription: string
  sceneDescription: string
  illustrationStyle: string
  referencePhotoUrl?: string
  pageNumber: number
  previousImages?: string[] // For consistency
}

export interface ImageGenerationOutput {
  imageUrl: string
  revisedPrompt: string
  metadata: {
    model: string
    size: string
    quality: string
    safetyChecked: boolean
  }
}

export interface CharacterDescription {
  // Physical features
  age: number
  gender: string
  skinTone: string
  hairColor: string
  hairStyle: string
  hairLength: string
  eyeColor: string
  eyeShape: string
  faceShape: string
  height: string
  build: string
  
  // Clothing (typical)
  clothingStyle: string
  clothingColors: string[]
  
  // Unique features
  uniqueFeatures: string[]
  
  // Expression and personality
  typicalExpression: string
  personalityTraits: string[]
}

export interface CharacterAnalysis {
  // From reference photo analysis
  detectedFeatures: {
    age: number
    gender: string
    skinTone: string
    hairColor: string
    hairStyle: string
    eyeColor: string
    faceShape: string
  }
  // Combined with user input
  finalDescription: CharacterDescription
  confidence: number
}

export interface StyleConfig {
  name: string
  basePrompt: string
  artisticStyle: string
  medium: string // watercolor, digital, oil painting, etc.
  lighting: string
  colorScheme: string
  detailLevel: 'low' | 'medium' | 'high'
  mood: string
}

export interface NegativePrompt {
  general: string[]
  ageSpecific: {
    [key: string]: string[]
  }
  styleSpecific: {
    [key: string]: string[]
  }
}

// ============================================================================
// Feedback and Learning
// ============================================================================

export interface PromptFeedback {
  id: string
  bookId: string
  userId: string
  promptType: 'story' | 'image' | 'cover'
  promptVersion: string
  feedbackType: 'content' | 'quality' | 'consistency' | 'safety' | 'other'
  rating: 1 | 2 | 3 | 4 | 5
  comment?: string
  specific: {
    tooScary?: boolean
    inappropriate?: boolean
    inconsistent?: boolean
    tooSimple?: boolean
    tooComplex?: boolean
    perfect?: boolean
  }
  actionTaken?: string
  createdAt: Date
}

export interface PromptPerformance {
  version: string
  totalGenerations: number
  successRate: number
  averageRating: number
  averageTokens: number
  averageCost: number
  averageTime: number
  feedbackCount: number
  issueCount: number
  lastUpdated: Date
}

// ============================================================================
// A/B Testing
// ============================================================================

export interface ABTest {
  testId: string
  name: string
  description: string
  promptType: 'story' | 'image' | 'cover'
  startDate: Date
  endDate: Date
  status: 'draft' | 'active' | 'completed' | 'paused'
  variants: ABTestVariant[]
  successMetric: string
  results?: ABTestResults
}

export interface ABTestVariant {
  name: string
  version: string
  trafficPercentage: number
  description: string
}

export interface ABTestResults {
  winner?: string
  statistics: {
    [variantName: string]: {
      sampleSize: number
      successRate: number
      averageRating: number
      averageCost: number
      confidence: number
    }
  }
  conclusion: string
  nextSteps: string
}

// ============================================================================
// Template System
// ============================================================================

export interface PromptTemplate {
  version: PromptVersion
  type: 'story' | 'image' | 'cover'
  baseTemplate: string
  variables: TemplateVariable[]
  rules: TemplateRule[]
  examples: TemplateExample[]
}

export interface TemplateVariable {
  name: string
  type: 'string' | 'number' | 'boolean' | 'enum'
  required: boolean
  default?: any
  description: string
  validation?: string
}

export interface TemplateRule {
  condition: string
  action: string
  priority: number
}

export interface TemplateExample {
  input: any
  output: string
  description: string
  rating?: number
}

